#!/bin/sh
#
# Load modules
#

case "$1" in
  start)
	printf "Loading optional kernel modules"
        /sbin/modprobe rpi-ft5406
        /sbin/modprobe evdev
        /sbin/modprobe i2c-dev
        /sbin/modprobe i2c_bcm2835
	;;
  stop)
	printf "Unloading modules"
        /sbin/rmmod rpi-ft5406
        /sbin/rmmod evdev
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

