#!/bin/sh
#
# Starting UI
#

case "$1" in
  start)
	printf "Loading Application"
        /root/app </dev/null &>/tmp/stdout.txt &
	;;
  stop)
	printf "Nothing to do"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

